version: '3.7'
services:
  fastapi:
    image: rofar/first_test:latest
    container_name: fastapi_test
    shm_size: '2gb'
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_fastapi_db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - '../data/redis/data/:/data'
    command:
      - 'redis-server'

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - '8082:8081'
    depends_on:
      - redis
